#
# Package name and list of source files.
#

NAME=freeglut
CSRCS=\
freeglut_callbacks.c \
freeglut_cursor.c \
freeglut_display.c \
freeglut_ext.c \
freeglut_font.c \
freeglut_font_data.c \
freeglut_gamemode.c \
freeglut_geometry.c \
freeglut_glutfont_definitions.c \
freeglut_init.c \
freeglut_main.c \
freeglut_menu.c \
freeglut_misc.c \
freeglut_overlay.c \
freeglut_state.c \
freeglut_stroke_mono_roman.c \
freeglut_stroke_roman.c \
freeglut_structure.c \
freeglut_teapot.c \
freeglut_videoresize.c \
freeglut_window.c \
freeglut_joystick.c


USER_CFLAGS=-DHAVE_CONFIG_H



#
# GAPS library makefile
#

include ../../scripts/Makefile.pkgs



